export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const DELETE_LIST = "DELETE_LIST";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

export const ERROR_LOG = "ERROR_LOG";

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGN_UP_ATTEMPT = "SIGN_UP_ATTEMPT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const CONTACT_US_SUBMITTED = "CONTACT_US_SUBMITTED";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";

export const ADD_STOCK_FAIL = "ADD_STOCK_FAIL";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_ATTEMPT = "ADD_STOCK_ATTEMPT";

export const DELETE_STOCK_ATTEMPT = "DELETE_STOCK_ATTEMPT";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAIL = "DELETE_STOCK_FAIL";

export const SET_SHIPPING_ATTEMP = "SET_SHIPPING_ATTEMP";
export const SET_SHIPPING_SUCCESS = "SET_SHIPPING_SUCCESS";
export const SET_SHIPPING_FAIL = "SET_SHIPPING_FAIL";




